newbok1d/bokapp/api/urls.py
from django.conf.urls import url
from . import viewsapi
from django.urls import path


app_name = 'api'
urlpatterns = [
    path('questions/', viewsapi.BooksAPIView.as_view()),
]

newbok1d/bokapp/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'bokapp'
urlpatterns = [
    # post views
    path('bokapp/book_search/', views.booksearch, name='book_search'),
    path('list/', IndexView.as_view(), name="book_list"),
    path('bokapp/book_filter/', views.bookfilter, name='book_filter'),
    path('add/', BooksCreateView.as_view(), name="books-add"),
    path('update/<int:pk>', BooksUpdateView.as_view(), name="books-update"),
    path('delete/<int:pk>/', BooksDeleteView.as_view(), name='delete'),

]

newbok1d/webbook/urls.py
from django.contrib import admin
from django.urls import path, include


admin.autodiscover()


urlpatterns = [
    path('', include('bokapp.urls', namespace='bokapp')),
    path('admin/', admin.site.urls),
    path('api/', include("bokapp.api.urls", namespace='api'))
]

newbok1d/bokapp/models.py
from django.db import models
from django.urls import reverse_lazy, reverse

class Books(models.Model):


    title = models.CharField(max_length=250)
    authors = models.CharField(max_length=100)
    publisheddate = models.PositiveSmallIntegerField()
    isbn_number = models.CharField(max_length=13)
    pagecount = models.PositiveSmallIntegerField()
    language = models.CharField(max_length=2)
    imagelinks = models.URLField(max_length=200)



    def get_absolute_url(self):
        return reverse('list-view', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

newbok1d/bokapp/forms.py
from django import forms
import requests
import json
from .models import Books

class BookUpdateForm(forms.Form):

    title = forms.CharField(max_length=250)
    authors = forms.CharField(max_length=100)
    publisheddate = forms.IntegerField(min_value=1500, max_value=2030)
    isbn_number = forms.IntegerField(min_value=9780000000000, max_value=9799999999999)
    pagecount = forms.IntegerField(min_value=1, max_value=10000)
    language = forms.CharField(max_length=2)
    imagelinks = forms.URLField(max_length=200)

    class Meta:
        model = Books
        fields = '__all__'


class BookSearchForm(forms.Form):

    search_word = forms.CharField(max_length=50, required=False)
    title = forms.CharField(max_length=250, required=False)
    authors = forms.CharField(max_length=100, required=False)
    isbn_number = forms.IntegerField(required=False)

    def search(self):

        result = {}
        search_word = self.cleaned_data['search_word']
        title = self.cleaned_data['title']
        authors = self.cleaned_data['authors']
        isbn_number = self.cleaned_data['isbn_number']

        if search_word:
            s_word = search_word
        else:
            s_word = ""

        if title:
            titl_e = "+intitle:{}".format(title)
        else:
            titl_e = ""

        if authors:
            author_s = "+inauthor:{}".format(authors)
        else:
            author_s = ""

        if isbn_number:
            isb_n = "+isbn:{}".format(isbn_number)
        else:
            isb_n = ""

        url = "https://www.googleapis.com/books/v1/volumes?q={}".format(s_word) + author_s + titl_e + isb_n

        response = requests.get(url)

        if response.status_code == 200:  # SUCCESS
            result = json.loads(response.text)
        elif response.status_code > 200:
            result['message'] = False
        return result

newbok1d/bokapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Books
from .filters import BooksFilter
from .forms import BookSearchForm, BookUpdateForm
from django.contrib import messages
from django.views.generic import ListView
from django.views.generic import UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy


class BooksCreateView(CreateView):
    model = Books
    fields = "__all__"
    template_name = 'bokapp/books/books_add.html'
    success_url = reverse_lazy('bokapp:book_list')

    def form_valid(self, form):

        if form.cleaned_data['title'].isalpha() == "":
            form.add_error('title', 'this field must be filled')
            return self.form_invalid(form)
        if form.cleaned_data['authors'].isalpha() == "":
            form.add_error('authors', 'this field must be filled')
            return self.form_invalid(form)
        if form.cleaned_data['publisheddate'] < 1500 or form.cleaned_data['publisheddate'] > 2030:
            form.add_error('publisheddate', 'this field: min_value=1500, max_value=2030')
            return self.form_invalid(form)
        if form.cleaned_data['pagecount'] < 1 or form.cleaned_data['pagecount'] > 10000:
            form.add_error('pagecount', 'this field: min_value=1, max_value=10000')
        if len(str(form.cleaned_data['isbn_number'])) != 13 or str(form.cleaned_data['isbn_number']).isdigit() is False:
            form.add_error('isbn_number', 'in this field must be only 13 numbers')
            return self.form_invalid(form)
        if form.cleaned_data['language'].isalpha() is False:
            form.add_error('language', 'in this field must be only 2 letters')
            return self.form_invalid(form)
        return super().form_valid(form)


class BooksUpdateView(UpdateView):
    model = Books
    fields = "__all__"
    template_name = 'bokapp/books/books_update.html'
    success_url = reverse_lazy('bokapp:book_list')

    def form_valid(self, form):
        if len(str(form.cleaned_data['isbn_number'])) != 13 or str(form.cleaned_data['isbn_number']).isdigit() is False:
            form.add_error('isbn_number', 'in this feiel must be only 13 numbers')
            return self.form_invalid(form)
        if form.cleaned_data['language'].isalpha() is False:
            form.add_error('language', 'in this feield must be only 2 letters')
            return self.form_invalid(form)
        return super().form_valid(form)


class IndexView(ListView):
    model = Books
    queryset = Books.objects.all()
    template_name = 'bokapp/books/books_list.html'
    context_object_name = 'books'


class BooksDeleteView(DeleteView):
    model = Books
    pk_url_kwarg = "pk"
    template_name = 'bokapp/books/confirm_delete.html'
    success_url = reverse_lazy('bokapp:book_list')


def bookfilter(request):
    books_list = Books.objects.all()
    books_filter = BooksFilter(request.GET, queryset=books_list)
    return render(request,
                  'bokapp/books/book_filter.html',
                  {'filter': books_filter})


def booklist(request):
    object_list = Books.objects.all()
    books = object_list

    return render(request,
                  'bokapp/books/booklist.html',
                  {'books': books})


def booksearch(request):

    number_of_new_books = 0
    if request.method == 'GET':
        form = BookSearchForm(request.GET)
        if form.is_valid():
            search_result = form.search()

            if len(search_result) < 3 or search_result['totalItems'] == 0 or search_result is False:
                messages.add_message(request, messages.INFO, 'No entry founded')
            else:
                for i in range(len(search_result['items'])):
                    searched_results = (search_result['items'][i]['volumeInfo'])
                    book_verification_list = [keeys for keeys in searched_results.keys()]

                    if "title" in book_verification_list:
                        title = searched_results['title']
                    else:
                        title = "No title"

                    authors = ""
                    try:
                        if len(searched_results['authors']):
                            for k in range(len(searched_results['authors'])):
                                authors += searched_results['authors'][k]
                        else:
                            authors = searched_results['authors'][0]
                    except KeyError:
                        pass

                    isbn_13 = ""
                    for item in searched_results['industryIdentifiers']:
                        if item['type'] == "isbn_13":
                            isbn_13 = item['identifier']
                        elif item['type'] == "OTHER":
                            isbn_13 = item['identifier']

                    if "pageCount" in book_verification_list:
                        pageCount = (searched_results['pageCount'])
                    else:
                        pageCount = 0

                    if "imageLinks" in book_verification_list:
                        imageLinks = (searched_results['imageLinks']['smallThumbnail'])
                    else:
                        imageLinks = "https://via.placeholder.com/150x200"

                    language = (searched_results['language'])

                    try:
                        publishedDate = searched_results['publishedDate'][:4]
                    except KeyError:
                        pass

                    if len(publishedDate) == 4 and len(authors) <= 100:
                        book = Books(
                            title=title,
                            authors=authors,
                            publisheddate=publishedDate,
                            isbn_number=isbn_13,
                            pagecount=pageCount,
                            imagelinks=imageLinks,
                            language=language
                        )
                        book.save()
                        number_of_new_books += 1

            books = Books.objects.all()
            present_books = len(books) - number_of_new_books

            if len(Books.objects.all()[present_books:]) > 0:
                books = Books.objects.all()[present_books:]
                #print("added_books---->>", books)
                return render(request,
                              'bokapp/books/findsearch.html',
                              {'books': books})
    else:
        form = BookSearchForm()

    return render(request,
                  'bokapp/books/book_search.html',
                  {'form': form})

newbok1d/bokapp/templates/bokapp/books/book_filter.html
{% extends "bokapp/base_filter.html" %}
{% load widget_tweaks %}

{% block contentfilter %}
<div class="container py-5" >
  <div id="filter" style="text-align: center; padding-bottom: 20px;">
  <h1 style="margin-top: 0; color: orange; font-weight: bold; font-size: 4rem" >Filtering books</h1></div>
   <form action="" method="get">
    <div class="well" style="color: whitesmoke;">
      <div class="row">
        <div class="form-group col-sm-3 col-md-3">
          {{ filter.form.title.label_tag }}
          {% render_field filter.form.title class="form-control" %}
          </div>
        <div class="form-group col-sm-3 col-md-3">
          {{ filter.form.authors.label_tag }}
          {% render_field filter.form.authors class="form-control" %}
        </div>
        <div class="form-group col-sm-3 col-md-3">
          {{ filter.form.language.label_tag }}
          {% render_field filter.form.language class="form-control" %}
        </div>
        <div class="form-group col-sm-3 col-md-3">
          {{ filter.form.release__joined_year.label_tag }}
          {% render_field filter.form.release__joined_year class="form-control" %}
        </div>
           <div class="form-group col-sm-3 col-md-3">
          {{ filter.form.release_year__gt.label_tag }}
          {% render_field filter.form.release_year__gt class="form-control" %}
        </div>
           <div class="form-group col-sm-3 col-md-3">
          {{ filter.form.release_year__lt.label_tag }}
          {% render_field filter.form.release_year__lt class="form-control" %}
        </div>
       </div>
      <div id="bat" style="text-align: center; padding-bottom: 20px; padding-top: 20px">
      <button type="submit" class="btn btn-primary" style="margin-bottom: 20px;">
        <span class="glyphicon glyphicon-search"></span> Search
      </button>
     </div>
  </form>

  <table  class="table table-borderless table-dark" style="text-align: center;">
         <thead class="thead-dark">
            <tr>
              <th scope = "col"> # </th>
              <th>Title</th>
              <th>Authors</th>
              <th>PublishedDate</th>
              <th>ISBN_number</th>
              <th>PageCount</th>
              <th>ImageLinks</th>
              <th>Language</th>
             </tr>
    </thead>

      <tbody>
    {% for book in filter.qs %}
        <tr class="text-center-row">
          <td scope="row">{{forloop.counter}}</td>
          <td>{{ book.title }}</td>
          <td>{{ book.authors }}</td>
          <td>{{ book.publisheddate }}</td>
          <td>{{book.isbn_number}}</td>
          <td>{{book.pagecount}}</td>
          <td><a target="_blank" href={{book.imagelinks}}>
          <img src={{book.imagelinks}} alt="no_picture" width="100" height="140">
          </a>
          </td>
          <td>{{ book.language}}</td>
        </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

newbok1d/bokapp/templates/bokapp/books/book_search.html
{% extends "bokapp/base_search.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block main %}

<div class="formtext">
    <div class="nag" style="padding-top: 5px; padding-bottom: 30px">
        <h1>Books searching</h1></div>
<form  method="get">
    {% csrf_token %}
    {{ form|crispy }}
    <button  type="submit"  class="btn btn-success">Serach and Import</button>
</form>
</div>
{% endblock %}

newbok1d/bokapp/templates/bokapp/books/books_add.html
{% extends "bokapp/base_update.html" %}


{% block content %}

<div class="container pt-5">
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form.visible_fields %}
            <div class="form-group">
                <label>{{field.label}}</label>
                {{field}}
                {% for error in field.errors %}
                    <span class="help-block" style="color:red">{{error}}</span>
                {% endfor %}
            </div>
        {% endfor %}
        <div>
            <button type="submit" class="btn btn-success">Submit</button>
            <a href="{% url 'bokapp:book_list' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

newbok1d/bokapp/templates/bokapp/books/books_list.html
{% extends "bokapp/base_list.html" %}
{% load widget_tweaks %}

{% block content %}
{{ books.refresh_from_db}}
<div class="container py-5" >
  <table class="table table-borderless table-dark">
      <tbody>

    {% for book in books %}

        <tr class="text-center-row">
          <td>id/{{book.id}}</td>
          <td>{{ book.title }}</td>
          <td>{{ book.authors }}</td>
          <td>{{ book.publisheddate }}</td>
          <td>{{book.isbn_number}}</td>
          <td>{{book.pagecount}}</td>
          <td>{{ book.language}}</td>
          <td><a class="btn btn-sm btn-outline-primary" href="{% url 'bokapp:books-update' book.id %}">Update</a>
          </td>
            <td>
              <a href="{% url 'bokapp:delete' book.id %}" role="button" class="btn btn-sm btn-outline-danger">Delete</a>
          </td>
        </tr>
    {% endfor %}
    </tbody>

  </table>
</div>
{% endblock %}

newbok1d/bokapp/templates/bokapp/books/books_update.html
{% extends "bokapp/base_update.html" %}
{% load crispy_forms_tags %}


{% block content %}

<div class="card">
    <div class="card-header">
        <h5 class="card-title">Book Update {{book.id}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Update</button>
        </form>
    </div>
</div>
{% endblock %}

newbok1d/bokapp/templates/bokapp/books/confirm_delete.html
{% extends "bokapp/base_update.html" %}
{% load crispy_forms_tags %}


{% block content %}

<div class="container py-5" >
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <p>Are you sure you want to delete "{{object}}"?</p>
            <input type="submit" value="Confirm">
        </form>
    </div>
</div>
{% endblock %}

newbok1d/bokapp/templates/bokapp/books/findsearch.html
{% extends "bokapp/base_findsearch.html" %}

{% block content %}

<div class="container py-5">
        <div class="col-lg-7 mx-auto" style="padding-top: 20px; padding-bottom: 50px">
            <h1 class="display-4" >Imported Books</h1>
        </div>

{% for book in books %}
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <!-- List group-->
            <ul class="list-group shadow">
                <!-- list group item-->
                <li class="list-group-item" style="border-color:blueviolet">
                    <!-- Custom content-->
                    <div class="media align-items-lg-center flex-column flex-lg-row p-3">
                        <div class="media-body order-2 order-lg-1">
                            <h5 class="mt-0 font-weight-bold mb-2">{{ book.title }}</h5>
                            <div class="d-flex align-items-center justify-content-between mt-1">
                                <h6 class="font-weight-bold my-2">{{ book.authors }}</h6>
                            </div>
                            <p class="font-italic text-muted mb-0 small">{{ book.publisheddate }}  | ISBN {{ book.isbn_number }} |  {{ book.pagecount}} pages | {{ book.language}}</p>

                        </div><img src={{book.imagelinks}}  alt="Generic placeholder image" height="196px" class="ml-lg-5 order-1 order-lg-2">
                    </div> <!-- End -->
                </li> <!-- End -->
                <!-- list group item-->
            </ul> <!-- End -->
        </div>
    </div>
{% endfor %}
</div>

 {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <p class="{{ message.tags }}"> <span style="color: orangered">{{ message }}</span></p>
    {% endfor %}
  </ul>
 {% endif %}
{% endblock %}