newbok1d/bokapp/api/urls.py
from django.conf.urls import url
from . import viewsapi
from django.urls import path


app_name = 'api'
urlpatterns = [
    path('questions/', viewsapi.BooksAPIView.as_view()),
]

newbok1d/bokapp/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'bokapp'
urlpatterns = [
    # post views
    path('bokapp/book_search/', views.booksearch, name='book_search'),
    path('list/', IndexView.as_view(), name="book_list"),
    path('bokapp/book_filter/', views.bookfilter, name='book_filter'),
    path('add/', BooksCreateView.as_view(), name="books-add"),
    path('update/<int:pk>', BooksUpdateView.as_view(), name="books-update"),
    path('delete/<int:pk>/', BooksDeleteView.as_view(), name='delete'),

]

newbok1d/webbook/urls.py
from django.contrib import admin
from django.urls import path, include


admin.autodiscover()


urlpatterns = [
    path('', include('bokapp.urls', namespace='bokapp')),
    path('admin/', admin.site.urls),
    path('api/', include("bokapp.api.urls", namespace='api'))
]

newbok1d/bokapp/models.py
from django.db import models
from django.urls import reverse_lazy, reverse

class Books(models.Model):


    title = models.CharField(max_length=250)
    authors = models.CharField(max_length=100)
    publisheddate = models.PositiveSmallIntegerField()
    isbn_number = models.CharField(max_length=13)
    pagecount = models.PositiveSmallIntegerField()
    language = models.CharField(max_length=2)
    imagelinks = models.URLField(max_length=200)



    def get_absolute_url(self):
        return reverse('list-view', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

newbok1d/bokapp/forms.py
from django import forms
import requests
import json
from .models import Books

class BookUpdateForm(forms.Form):

    title = forms.CharField(max_length=250)
    authors = forms.CharField(max_length=100)
    publisheddate = forms.IntegerField(min_value=1500, max_value=2030)
    isbn_number = forms.IntegerField(min_value=9780000000000, max_value=9799999999999)
    pagecount = forms.IntegerField(min_value=1, max_value=10000)
    language = forms.CharField(max_length=2)
    imagelinks = forms.URLField(max_length=200)

    class Meta:
        model = Books
        fields = '__all__'


class BookSearchForm(forms.Form):

    search_word = forms.CharField(max_length=50, required=False)
    title = forms.CharField(max_length=250, required=False)
    authors = forms.CharField(max_length=100, required=False)
    isbn_number = forms.IntegerField(required=False)

    def search(self):

        result = {}
        search_word = self.cleaned_data['search_word']
        title = self.cleaned_data['title']
        authors = self.cleaned_data['authors']
        isbn_number = self.cleaned_data['isbn_number']

        if search_word:
            s_word = search_word
        else:
            s_word = ""

        if title:
            titl_e = "+intitle:{}".format(title)
        else:
            titl_e = ""

        if authors:
            author_s = "+inauthor:{}".format(authors)
        else:
            author_s = ""

        if isbn_number:
            isb_n = "+isbn:{}".format(isbn_number)
        else:
            isb_n = ""

        url = "https://www.googleapis.com/books/v1/volumes?q={}".format(s_word) + author_s + titl_e + isb_n

        response = requests.get(url)

        if response.status_code == 200:  # SUCCESS
            result = json.loads(response.text)
        elif response.status_code > 200:
            result['message'] = False
        return result

newbok1d/bokapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Books
from .filters import BooksFilter
from .forms import BookSearchForm, BookUpdateForm
from django.contrib import messages
from django.views.generic import ListView
from django.views.generic import UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy


class BooksCreateView(CreateView):
    model = Books
    fields = "__all__"
    template_name = 'bokapp/books/books_add.html'
    success_url = reverse_lazy('bokapp:book_list')

    def form_valid(self, form):

        if form.cleaned_data['title'].isalpha() == "":
            form.add_error('title', 'this field must be filled')
            return self.form_invalid(form)
        if form.cleaned_data['authors'].isalpha() == "":
            form.add_error('authors', 'this field must be filled')
            return self.form_invalid(form)
        if form.cleaned_data['publisheddate'] < 1500 or form.cleaned_data['publisheddate'] > 2030:
            form.add_error('publisheddate', 'this field: min_value=1500, max_value=2030')
            return self.form_invalid(form)
        if form.cleaned_data['pagecount'] < 1 or form.cleaned_data['pagecount'] > 10000:
            form.add_error('pagecount', 'this field: min_value=1, max_value=10000')
        if len(str(form.cleaned_data['isbn_number'])) != 13 or str(form.cleaned_data['isbn_number']).isdigit() is False:
            form.add_error('isbn_number', 'in this field must be only 13 numbers')
            return self.form_invalid(form)
        if form.cleaned_data['language'].isalpha() is False:
            form.add_error('language', 'in this field must be only 2 letters')
            return self.form_invalid(form)
        return super().form_valid(form)


class BooksUpdateView(UpdateView):
    model = Books
    fields = "__all__"
    template_name = 'bokapp/books/books_update.html'
    success_url = reverse_lazy('bokapp:book_list')

    def form_valid(self, form):
        if len(str(form.cleaned_data['isbn_number'])) != 13 or str(form.cleaned_data['isbn_number']).isdigit() is False:
            form.add_error('isbn_number', 'in this feiel must be only 13 numbers')
            return self.form_invalid(form)
        if form.cleaned_data['language'].isalpha() is False:
            form.add_error('language', 'in this feield must be only 2 letters')
            return self.form_invalid(form)
        return super().form_valid(form)


class IndexView(ListView):
    model = Books
    queryset = Books.objects.all()
    template_name = 'bokapp/books/books_list.html'
    context_object_name = 'books'


class BooksDeleteView(DeleteView):
    model = Books
    pk_url_kwarg = "pk"
    template_name = 'bokapp/books/confirm_delete.html'
    success_url = reverse_lazy('bokapp:book_list')


def bookfilter(request):
    books_list = Books.objects.all()
    books_filter = BooksFilter(request.GET, queryset=books_list)
    return render(request,
                  'bokapp/books/book_filter.html',
                  {'filter': books_filter})


def booklist(request):
    object_list = Books.objects.all()
    books = object_list

    return render(request,
                  'bokapp/books/booklist.html',
                  {'books': books})


def booksearch(request):

    number_of_new_books = 0
    if request.method == 'GET':
        form = BookSearchForm(request.GET)
        if form.is_valid():
            search_result = form.search()

            if len(search_result) < 3 or search_result['totalItems'] == 0 or search_result is False:
                messages.add_message(request, messages.INFO, 'No entry founded')
            else:
                for i in range(len(search_result['items'])):
                    searched_results = (search_result['items'][i]['volumeInfo'])
                    book_verification_list = [keeys for keeys in searched_results.keys()]

                    if "title" in book_verification_list:
                        title = searched_results['title']
                    else:
                        title = "No title"

                    authors = ""
                    try:
                        if len(searched_results['authors']):
                            for k in range(len(searched_results['authors'])):
                                authors += searched_results['authors'][k]
                        else:
                            authors = searched_results['authors'][0]
                    except KeyError:
                        pass

                    isbn_13 = ""
                    for item in searched_results['industryIdentifiers']:
                        if item['type'] == "isbn_13":
                            isbn_13 = item['identifier']
                        elif item['type'] == "OTHER":
                            isbn_13 = item['identifier']

                    if "pageCount" in book_verification_list:
                        pageCount = (searched_results['pageCount'])
                    else:
                        pageCount = 0

                    if "imageLinks" in book_verification_list:
                        imageLinks = (searched_results['imageLinks']['smallThumbnail'])
                    else:
                        imageLinks = "https://via.placeholder.com/150x200"

                    language = (searched_results['language'])

                    try:
                        publishedDate = searched_results['publishedDate'][:4]
                    except KeyError:
                        pass

                    if len(publishedDate) == 4 and len(authors) <= 100:
                        book = Books(
                            title=title,
                            authors=authors,
                            publisheddate=publishedDate,
                            isbn_number=isbn_13,
                            pagecount=pageCount,
                            imagelinks=imageLinks,
                            language=language
                        )
                        book.save()
                        number_of_new_books += 1

            books = Books.objects.all()
            present_books = len(books) - number_of_new_books

            if len(Books.objects.all()[present_books:]) > 0:
                books = Books.objects.all()[present_books:]
                #print("added_books---->>", books)
                return render(request,
                              'bokapp/books/findsearch.html',
                              {'books': books})
    else:
        form = BookSearchForm()

    return render(request,
                  'bokapp/books/book_search.html',
                  {'form': form})

newbok1d/bokapp/templates/bokapp/base3.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% block meta_tags %}{% endblock %}
  <title>{% block title %}{% endblock %}</title>

  {% block css %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  {% endblock %}

  {% block custom_css %}
  {% endblock %}
</head>
<body>

  {% block navbar %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="#">All About Django</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% endblock %}

  <div class="container mt-4">
  {% block container %}
  {% endblock %}
  </div>

  {% block js %}
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  {% endblock %}

  {% block custom_js %}
  {% endblock %}
</body>
</html>

newbok1d/bokapp/templates/bokapp/base_filter.html
{% load bokapp_tags %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <!---<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">-->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'bokapp/style.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<style>
</style>

</head>
<body id="bokfilter">

{% block contentfilter %}
{% endblock %}

</body>

</html>

newbok1d/bokapp/templates/bokapp/base_findsearch.html
{% load bokapp_tags %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'bokapp/style.css' %}">

<style>

</style>
</head>
<body id="searchformanswer">

  <div class="constant">
          {% block content %}"
          {% endblock %}
        </div>
  </body>

</html>

newbok1d/bokapp/templates/bokapp/base_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>List</title>
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<style>
h2{
  font-size: 25px;
}
</style>

</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="#">BOOKS</a>
      <a class="btn btn-secondary" href="{% url 'bokapp:books-add' %}">Add book</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href=#>
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=#></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12">

        {% block content %}

        {% endblock %}
      </div>
    </div>
  </div>
  <!-- Bootstrap core JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.slim.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script></body>
  <script src="https://getbootstrap.com/docs/4.0/assets/js/vendor/holder.min.js"></script>
</html>

newbok1d/bokapp/templates/bokapp/base_search.html
{% load bokapp_tags %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <!---<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">-->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'bokapp/style.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<style>

</style>
</head>
<body id="searchform">

  <div class="container d-flex h-100" style="justify-content: center">
      <div class="row justify-content-center">
        <div class="col-12">
          {% block main %}
          {% endblock %}
        </div>
      </div>
    </div>

</body>

</html>

newbok1d/bokapp/templates/bokapp/base_update.html
{% load bokapp_tags %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'bokapp/style.css' %}">
    <style>

div h1 {
  background-color: transparent;
  display:inline;
  color: white;
}

</style>
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>

</body>
</html>